version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
	newline = true

	[[blocks.segments]]
		type = 'path'
		style = 'plain'
		foreground = 'blue'
		background = 'transparent'
		template = '{{ .Path }}'

		[blocks.segments.properties]
			style = 'full'
	
	[[blocks.segments]]
		type = 'git'
		style = 'plain'
		foreground = '#6c6c6c'
		background = 'transparent'
		template = ' {{ .HEAD }}'

		[blocks.segments.properties]
			branch_icon = ''

[[blocks]]
	type = 'prompt'
	alignment = 'left'

	[[blocks.segments]]
		type = 'text'
		style = 'plain'
		foreground = 'blue'
		background = 'transparent'
		template = ' >'
