set nocompatible

" -- Options -- {{{
" ui
set number cursorline showmatch termguicolors
set signcolumn=yes
set laststatus=2
" has most of the sections of what nvim's lualine has
set statusline=\ %t\ %m%=\ %P\ %l:%c\ 
" set helpheight=%{min([20, winheight(0)])}

" tabs & identation
set tabstop=2 shiftwidth=2

" search settings
set ignorecase smartcase hlsearch incsearch

" misc.
set mouse=nv
set nowrap noswapfile
set foldmethod=marker

set splitright splitbelow

set clipboard+=unnamedplus

set completeopt=menu,popup,noinsert
set wildignorecase
set formatoptions=jtcl
" }}}
set shortmess-=I

" -- Keymaps -- {{{
nnoremap "\<Space>" <Nop>
let g:mapleader = " "
let g:localmapleader = "\\"

nnoremap <silent> <leader>wt :set wrap!<CR>
nnoremap <silent> <leader>sc :setlocal spell!<CR>

tnoremap <Esc> <C-\\><C-n>

" *sometimes* emacs is right {{{
inoremap <C-a> <C-o>^
inoremap <C-e> <C-o>$
inoremap <C-b> <C-o>h
inoremap <C-f> <C-o>l

cnoremap <C-a> <C-b>
" <C-e> is already end-of-line in cmd mode
cnoremap <C-b> <Left>
cnoremap <C-f> <Right>
" }}}

nnoremap <C-k> <C-w>k
nnoremap <C-j> <C-w>j
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

nnoremap <silent> <leader>nh :nohlsearch<CR>

vnoremap < <gv
vnoremap > >gv

nnoremap <silent> [t :tabprev<CR>
nnoremap <silent> ]t :tabnext<CR>
" }}}

" ./colors/catppuccin_mocha.vim from
"   https://github.com/catppuccin/vim/blob/main/colors/catppuccin_mocha.vim
colorscheme catppuccin_mocha

filetype plugin indent on
syntax on
