set nocompatible

" -- Options -- {{{1
" ui
set number cursorline showmatch termguicolors
set signcolumn=yes
set laststatus=2
set helpheight=15

" tabs & identation
set tabstop=2 shiftwidth=2

" search settings
set ignorecase smartcase hlsearch incsearch

" misc.
set mouse=nv
set nowrap noswapfile
set foldmethod=marker

set splitright splitbelow

set clipboard+=unnamedplus

set completeopt=menu,popup,noinsert
set wildignorecase
set formatoptions=jtcl

set fillchars+=vert:│

set viminfofile='$XDG_STATE_HOME/vim/viminfo'

set shortmess-=I

" -- Keymaps -- {{{1
nnoremap <Space> <Nop>
let g:mapleader = ' '
let g:localmapleader = "\\"

nnoremap <silent> <leader>wt <cmd>set wrap!<CR>
nnoremap <silent> <leader>sc <cmd>setlocal spell!<CR>

nnoremap <silent> <leader>nh <cmd>nohl<CR>

tnoremap <Esc> <C-\><C-n>

" *sometimes* emacs is right {{{2
inoremap <C-a> <C-o>^
inoremap <C-e> <C-o>$
inoremap <C-b> <Left>
inoremap <C-f> <Right>

cnoremap <C-a> <C-b>
" <C-e> is already end-of-line in cmd mode
cnoremap <C-b> <Left>
cnoremap <C-f> <Right>
" }}}2

nnoremap <C-k> <C-w>k
nnoremap <C-j> <C-w>j
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

vnoremap < <gv
vnoremap > >gv

nnoremap <silent> <A-j> <cmd>m .+1<CR>==
nnoremap <silent> <A-k> <cmd>m .-2<CR>==

nnoremap n nzz
nnoremap N Nzz

nnoremap <silent> [t <cmd>tabprev<CR>
nnoremap <silent> ]t <cmd>tabnext<CR>
" }}}

" -- Plugins --
" disable some builtin plugins
let g:loaded_gzip = 1
let g:loaded_tarPlugin = 1
let g:loaded_tutor_mode_plugin = 1
let g:loaded_zipPlugin = 1
let g:loaded_2html_plugin = 1

" ./colors/catppuccin_mocha.vim from
"   https://github.com/catppuccin/vim/blob/main/colors/catppuccin_mocha.vim
colorscheme catppuccin_mocha

" statusline
set statusline=%{%GetStlLeft()%}%=%{GetStlRight()}
set noshowmode

" file explorer
let g:netrw_dirhistmax = 0
nnoremap <silent> - :Fexplore<CR>

" language support
filetype plugin indent on
syntax on

" vim: set ts=2 sw=2
